### ISSUE TITLE
Help with setup needed

### ISSUE THREAD

**Issue by ghost** [dashpay/dash-abe#9]
Hi i just fixed the database (mysql)
And enabled RPC (with password)

And i'm now running into this problem:

Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 1, 'chain_id': 15, 'loader': u'rpc', 'conf': None, 'dirname': u'/home/aush0k/.dashcore', 'id': 9L}
Traceback (most recent call last):
File "Abe/DataStore.py", line 2566, in catch_up
if not store.catch_up_rpc(dircfg):
File "Abe/DataStore.py", line 2768, in catch_up_rpc
block_hash = chain.ds_block_header_hash(ds)
File "Abe/Chain/init.py", line 139, in ds_block_header_hash
ds.input[ds.read_cursor : ds.read_cursor + 80])
File "Abe/Chain/X11Chain.py", line 26, in block_header_hash
import dash_hash
ImportError: No module named dash_hash

This is my datadir config:
datadir += [{
"dirname": "/home/aush0k/.dashcore",
"loader": "rpc", # See the comments for default-loader below.
"chain": "Dash"
}]

Thanks in advance.

**Comment by ghost** [comment]
I tried both default-loader = rpc and the file thingy but still won't work :(

**Comment by UdjinM6** [comment]
Hi, `ImportError: No module named dash_hash` means you have to install https://github.com/dashpay/dash_hash

**Comment by ghost** [comment]
Thank you so much ! I did not notice that in any requirements :D
